name = "vmtp-worker"
type = "javascript"

[build]
command = ""

[vars]
# Optional upstream HTTP endpoint to forward messages
# SERVER_URL = "https://example.com/vmtp"

[[kv_namespaces]]
# Uncomment and set your KV namespace id to enable persistence
# binding = "MESSAGES"
# id = "your-namespace-id"

